### ISSUE TITLE
Range on single mode

### ISSUE THREAD

**Issue by kl3sk** [wakirin/litepicker-module-ranges#2]
Great addition to the awesome Litepicker. Thanks wait for more modules.

A strange behaviour occurs on this module.
If Litepicker is in `singleMode: true` (no range used), this module allow range and Litepicker has strange behaviour.

Link to reproduce: https://jsfiddle.net/klesk/1qw5ps7m/

This may override the parent option or better can't define any ranges.

Thanks again

**Comment by wakirin** [comment]
Why are you trying to use ranges module in singleMode ?

**Comment by kl3sk** [comment]
I don't want to, I just forgot to remove this options and see want happens.

This behavior may be checked I think.

**Comment by wakirin** [comment]
Added in v0.0.4
https://github.com/wakirin/litepicker-module-ranges/blob/3bbec718f15a52caa294c68e7795d2223cafba18/src/index.ts#L43-L46

**Comment by kl3sk** [comment]
Very reactive as always thanks. I’ll try to send a feedback soon.

**Comment by kl3sk** [comment]
Sorry for the late answer.

Auto disabling works as intented 👍
